version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - errcheck  # Now enabled - all errors properly handled

formatters:
  enable:
    - goimports

formatters-settings:
  goimports:
    local-prefixes: github.com/nathanael/organizr

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
